### ISSUE TITLE
Offline Testing: document tests and provide script

### ISSUE THREAD

**Issue by margau** [chaosinventory/chaosinventory#37]
At the moment, we only test with isort and flake8 in the CI. We should document (and maybe simplify trough a script) the procedure to execute tests/lint/... offline, and encourage developers to do so. This avoids the hassle of doing "one-character-correction-commits".

The best place is probably over here: https://chaosinventory.readthedocs.io/projects/core/en/latest/dev/setup/index.html#working-on-and-with-the-code

We should also provide a script, which allows for local testing of "merge-readiness".

**Comment by e1mo** [comment]
My idea is to provide a default `pre-commit` hook. This could reside within a folder `hooks`. In the documentation we can add a note to do `cp hooks/pre-commit .git/hooks/pre-commit`. And if you want to check it during development just run `hooks/pre-commit`?

If that is fine with everyone I could implement it.

**Comment by margau** [comment]
I'm not sure if the script itself should reside in a git hook.
As a comparison, in node.js I would add a package script, executed by e.g. "npm run lint". That model would make execution even without git hooks easier, and the hook would execute that command. Additionally, a dedicated lint/test-script allows for more complex testing scenarios in the future.

**Comment by e1mo** [comment]
I think we should have at leas an easy option to integrate with native git hooks as this will throw up a big and bold message if the code you are going to commit does not pass the QA.

I personally am not the biggest fan of having the linting be done trough a cli command. To me, it does integrate deeply enough with the code to be run from e.g. `manage.py lint`. I feel as if this spot is reserved for e.G. unit tests.

And, for isort, it would be beneficial to prompt people to directly use the isort command since it provides automatic fixing of your code (possible in a interactive or non interactive fashion), which is rely valuable.

If our documentation would be like 

> copy this to your hooks, if you want to check run `xyz` and to fix it use `isort --interactive`

I think this could become a bit confusing.

But on the other hand, if all the linting would be withing one cli command updates to it would not require to manually update the git hook (especially annoying during branch-jumping).

I'm interested what the others have to say, maybe put it up for our next telephone conference?

**Comment by e1mo** [comment]
As a base for our next meeting, I wanted to lay down which tools are used for QA/CI, how they can and can not be used.

- **[isort](https://pycqa.github.io/isort/)**
    - Sort imports alphabetically and group by packages
    - Make imports relative if applicable
    - Group and warp long import lines this: https://github.com/chaosinventory/chaosinventory/blob/716a43b10aa3acdb755f0a09b3b387fdbe3d9fc1/src/chaosinventory/base/views/api.py#L6-L10
    - Can run in check mode (no changes are made) and interactively
        - CI runs in check mode: `isort --color -c .` (`--color` is just to make it easier to read, `-c` translates to `--check`, non zero exit if violations are found)
        - Automatic fixing by just calling `isort .`, interactive (accept / skip) fixing using `isort --interactive .`. If you only want to check individual files / folders replace `.` with the path.
- **[flake8](https://flake8.pycqa.org/en/latest/)**
    - Check if [pep8](https://pep8.org/) guidelines are followed
    - Has no automatic fixing support => could be done trough [hhatto/autopep8](https://github.com/hhatto/autopep8)

Theoretically, [nektos/act](https://github.com/nektos/act) can be used for testing locally using docker in an environment comparable to github actions based on the defined workflows. But... it brings a whole docker tail with it (including the space and performance overhead).

**Comment by e1mo** [comment]
We discussed this issue in our call, no one rely supported the integration in to the `mange.py` and we decided on documenting how to run it manually (and isort autofixing). Also, we decided on providing a shell script (that ca be used for the git hook) for everyone to use.

If there is further need for discussion, we could talk about it the next time.
